server:
  port: 8200

spring:
  application:
    name: consumer-user

eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候，使用服务的ip地址进行注册
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
